### PR TITLE
Added French Translation and edited a bit English locale

### PR DESCRIPTION
**Pull request by sylveon**
I added french locale, fixed "patch" instead of "path", and made remove from history more specific.

### CODE REVIEW

**Comment by Infocatcher** [comment]
> fixed "patch" instead of "path"

Oh, indeed, thanks.

> and made remove from history more specific.

I'm not sure, downloaded items will be also displayed in browsing history too. So, this is not only downloads history.

Also there is typo, missing `»`:
```xml
<!ENTITY dpt.override.showAllDownloads "Bouton « Afficher tout les téléchargements">
```

**Comment by charlesmilette** [comment]
> I'm not sure, downloaded items will be also displayed in browsing history too. So, this is not only downloads history.  

I just checked. When you delete an item from the downloads history, it also automatically removes it from history
> Also there is typo, missing »
Thanks. Fixed

**Comment by Infocatcher** [comment]
> When you delete an item from the downloads history, it also automatically removes it from history

And vice versa: you can remove it from browsing history to remove both items (internally there is only one global history, but some entries are marked as "downloaded").

So, "remove from <ins>downloads</ins> history" may confuse user because will be also removed from browsing history.

**Comment by charlesmilette** [comment]
Okay. Your choice. I'll correct it.

**Comment by Infocatcher** [comment]
Thanks!
One more thing please, extension description in <a href="https://github.com/Infocatcher/Download_Panel_Tweaker/blob/master/install.rdf">install.rdf</a>:
```xml
		<em:localized>
			<Description>
				<em:locale>fr</em:locale>
				<em:name>Download Panel Tweaker</em:name>
				<em:description>Some tweaks for built-in download panel</em:description>
				<em:creator>Infocatcher</em:creator>
				<em:contributor>Icon: based on icon from Farm-fresh icon set by FatCow Web Hosting + built-in Firefox download icon</em:contributor>
				<em:translator>Charles Milette</em:translator>
			</Description>
		</em:localized>
```

**Comment by charlesmilette** [comment]
Oh yeah. Forgot that one

**Comment by Infocatcher** [comment]
Merged, thanks.

**Comment by charlesmilette** [comment]
Are you soon going to release a new version to AMO?

**Pull request merged**
